BEGIN;

-- public schema
CREATE TABLE public.Types (
    id integer GENERATED ALWAYS AS IDENTITY,
    id_default integer GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE public.Constraints (
    con_pk_one integer,
    con_pk_two integer,
    con_nullable integer,
    con_not_nullable integer NOT NULL,
    con_default_null integer DEFAULT 4,
    con_default_not_null integer DEFAULT 5 NOT NULL,
    con_generated integer GENERATED ALWAYS AS (3) STORED,
    PRIMARY KEY (con_pk_one, con_pk_two)
);

-- public view
CREATE VIEW public.VIEW AS SELECT 'hello world';

-- test schema
CREATE SCHEMA test;
CREATE TABLE test.References (
    fk_single integer,
    fk_multiple_one integer,
    fk_multiple_two integer,
    FOREIGN KEY (fk_single) REFERENCES public.Types (id),
    FOREIGN KEY (fk_multiple_one, fk_multiple_two) REFERENCES public.Constraints(con_pk_one, con_pk_two)
);

COMMIT;
