-- public namespace
CREATE TABLE public.Account (
    id_always integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    is_not_nullable text NOT NULL,
    is_nullable text,
    is_generated integer GENERATED ALWAYS AS (id_always + 1) STORED
);
CREATE VIEW public.TestView AS SELECT 'Hello World';
CREATE TABLE public.Pet (
	fname text,
    lname text,
    PRIMARY KEY (fname, lname)
);

-- test namespace
CREATE SCHEMA test;
CREATE TABLE test.Account (
    id_default integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text_default text DEFAULT 'defaultVal',
    fk_single integer REFERENCES public.Account (id_always),
    fk_multiple_fname text,
    fk_multiple_lname text,
    FOREIGN KEY (fk_multiple_fname, fk_multiple_lname) REFERENCES public.Pet(fname, lname)
);