-- public schema
CREATE TABLE public.Types (
    id integer GENERATED ALWAYS AS IDENTITY,
    id_default integer GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE public.Constraints (
    id_one integer,
    id_two integer,
    nullable integer,
    not_nullable integer NOT NULL,
    generated integer GENERATED ALWAYS AS (3) STORED,
    PRIMARY KEY (id_one, id_two)
);

-- public view
CREATE VIEW public.VIEW AS SELECT 'hello world';

-- test schema
CREATE SCHEMA test;
CREATE TABLE test.References (
    fk_single integer,
    fk_multiple_one integer,
    fk_multiple_two integer,
    FOREIGN KEY (fk_single) REFERENCES public.Types (id),
    FOREIGN KEY (fk_multiple_one, fk_multiple_two) REFERENCES public.Constraints(id_one, id_two)
);
